### ISSUE TITLE
Build DIND cluster test environment (or something equivalent) in CI

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/ansible-role-k8s_manifests#1]
Currently the Molecule tests just run Ansible Lint and a syntax check. I would like to be able to run a full `molecule test` and have it build an instance, have Kubernetes running somewhere accessible (e.g. maybe using the DIND cluster?), and then apply some example manifests to that cluster.

This should be achievable (I was doing it in Travis CI for the project from which I extracted this role...), but I don't have time tonight to finish the work :P

**Comment by fabianvf** [comment]
Hey, I've actually done some work in this direction. Here's a molecule.yml that uses a `kind` cluster: 

https://github.com/fabianvf/k8s-ansible-operator-cookiecutter/blob/master/%7B%7Bcookiecutter.app_name%7D%7D/molecule/test-local/molecule.yml#L10
